name: Concurrency
on: [push] #triggers
concurrency:
  #This work flow triggers only once for any branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true #Existing will be cancelled and latest will be run
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: #stages
      - name: step1
        run: sleep 20