name: Dependency
on: [push]
jobs:
  #Job1 and Job4 are parellel. No dependency
  job1: #These should be unique
    runs-on: ubuntu-latest
    steps: #stages
      - name: step1
        run: echo "Hi, i'm from job-1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hi, i'm from job-2"
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hi, i'm from job3"

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hi, i'm from job-4"
