name: Self-hosted-runner
on: [push]
jobs:  # Pipeline. One workflow can have multiple pipelines
  hello:
    runs-on: self-hosted
    steps: #Stages
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: echo "Hello Github Actions"